# -*- coding: utf-8 -*-
"""ia2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JlXj0XtnPzyJTqnpCyx32bzse4g-v0hX
"""

!pip install pandas

import pandas as pd
import numpy as np

#1
arr=np.array([1,2,3,4,5,6,7,8,9])
minimum=np.min(arr)
print(f"minimum={minimum}")
maximum=np.max(arr)
print(f"maximum={maximum}")
s=np.sum(arr)
print(f"sum={s}")
av=np.mean(arr)
print(f"mean={av}")
st=np.std(arr)
print(f"std={st}")

#2
health_data = np.array([[160, 70, 30],   # height, weight, age for individual 1
                        [165, 65, 35],   # height, weight, age for individual 2
                        [170, 75, 40]])  # height, weight, age for individual 3


def norm(l):
  s=0
  for i in l:
    s=s+i
  return (s/len(l))

df=pd.DataFrame(health_data,columns=['height','weight','age'])
df=df-df.apply(norm,axis=0)
print(df)

#3
mark=np.array([[25,30,40,70],[56,54,44,-1],[88,66,7,88],[87,-1,54,45]])
df=pd.DataFrame(mark,columns=['eng','science','math','social'])
df[df!=-1]
x=df.iloc[:, -3:]
avg_score=x[x!=1].mean(axis=1)
print(avg_score)

# 4
arr=np.linspace(15,25,24)
print(arr)

#5
import numpy as np
daily_closing_prices = np.array([100, 102, 98, 105, 107, 110, 108, 112, 115, 118, 120])
window_size = 5
df=pd.DataFrame(daily_closing_prices)
df['rollavg']=df.rolling(window=5).mean()
print(df)

#6
#coviarce and mean
arr=np.empty((2,3),100)

#7
import numpy as np
properties_matrix = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
properties_matrix.t

#8
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
df=pd.DataFrame(arr)
df=df[df<=5]
print(df)

#9
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
        'Age': [25, 30, 35, 40, 45, 50, 55],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami', 'Boston'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR']}
df=pd.DataFrame(data)
filtered_df=df[df['Age']<45][df['Department']=='HR']

#10
data = {'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
        'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Sales': [70000, 50000, 30000, 40000, 60000]}

df=pd.DataFrame(data)
df['avg_salep']=df['Sales'].groupby(by=['Salesperson','Department']).mean().reset_index
df['avg_dept']=df['sales'].groupby(by='Department').agg('mean').reset_index()
print(df)

#11
data = {
    'Product': ['Apples', 'Bananas', 'Cherries', 'Dates', 'Elderberries', 'Flour', 'Grapes'],
    'Category': ['Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Bakery', 'Fruit'],
    'Price': [1.20, 0.50, 3.00, 2.50, 4.00, 1.50, 2.00],
    'Promotion': [True, False, True, True, False, True, False]
}

df=pd.DataFrame(data)
ans=df[df['Promotion']==False][df['Category']=='Fruits']
print(ans)

#12
employee_data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Finance', 'IT'],
    'Manager': ['John', 'Rachel', 'Emily', 'Rachel']
}

# Dataset of employee project assignments
project_data = {
    'Employee': ['Alice', 'Charlie', 'Eve'],
    'Project': ['P1', 'P3', 'P2']
}
df=pd.DataFrame(employee_data)
df1=pd.DataFrame(project_data)
merged=df.merge(df1,on='Employee',how='left')
print(merged)

#13
sport=pd.read_csv('/content/Q13_sports_team_stats.csv')
win=sport['Wins']/sport['GamesPlayed']

print(win)

#14
cus=pd.read_csv('/content/Q14_customer_purchases.csv')
cus
a=cus[cus['Date']<cus['LoyaltyProgramSignUp']].groupby(by='CustomerID').mean('PurchaseAmount')
b=cus[cus['Date']>cus['LoyaltyProgramSignUp']].groupby(by='CustomerID').mean('PurchaseAmount')
print(a)
print(b)
c=a.merge(b,on='CustomerID ',how='inner')
c=c[a_PurchaseAmount<PurchaseAmount]

#15
stu=pd.read_csv('/content/Q15_student_grades.csv')
ag=stu.groupby(by='Subject').mean('Grade')
ans=ag[ag['Grade']<70]
print(ans)