# -*- coding: utf-8 -*-
"""final_assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fobv_tGlGj7ZRibx5Nt0R-xsYPKV3KLt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#1
ipl=pd.read_csv('/content/Final Dataset - IPL.csv')

print(ipl.info())

print(ipl.head())

print(np.where(pd.isna(ipl)))

#2
print(np.where(pd.isna(ipl)))
#since there is no value with na we there is no need to do any processing,
#But even then as the missing data will be evry less we can simply drop it
ipl_d=ipl.dropna()

print(ipl_d)

a=ipl_d.duplicated().reset_index()
print(a['index'][a[0]==True])
# since no duplicate is present in the ipl_d dataframe there is no need to remove it

#3
#taking both innings score and wicket for numerical calculations
#so we can understand which and plan the innings according ly
mean_analysis=ipl_d['first_ings_score'].mean()
print('1st ings mean score',mean_analysis)
median_analysis=ipl_d['first_ings_wkts'].median()
print('1st ings mean wickets',median_analysis)
mode_analysis=ipl_d['second_ings_score'].mode()
print('2nd ings mode score',mode_analysis)
range_analysis=ipl_d['first_ings_wkts'].max()-ipl_d['first_ings_wkts'].min()
print('1st ings range wickets',range_analysis)
var_analysis=ipl_d['first_ings_wkts'].var()
print('1st ings variance wickets',var_analysis)
std_ana=ipl_d['first_ings_wkts'].std()
print('1st ings std wickets',var_analysis)

#4
toss=ipl_d.groupby('toss_decision').size().reset_index(name='toss')
toss
plt.pie(toss['toss'])
plt.legend(toss['toss_decision'])
plt.show()

top_scorer=ipl_d.groupby('top_scorer')['highscore'].sum().reset_index(name='score')
top_scorer=top_scorer.sort_values(by='score',ascending=False).head(5)
plt.bar(top_scorer['top_scorer'],height=top_scorer['score'])
plt.show()

sns.scatterplot(x='first_ings_wkts',y='second_ings_wkts',data=ipl_d)
plt.show()

#5
sns.lineplot(x='match_id',y='first_ings_score',data=ipl_d)
sns.lineplot(x='match_id',y='second_ings_score',data=ipl_d)
plt.legend()
plt.show()

avg_first_score=ipl_d.groupby('venue')['first_ings_score'].mean().reset_index(name='mean_1')
avg_second_score=ipl_d.groupby('venue')['second_ings_score'].mean().reset_index(name='mean_2')
plt.bar(x=avg_first_score['venue'],height=avg_first_score['mean_1'],label='1')
plt.bar(x=avg_second_score['venue'],height=avg_second_score['mean_2'],label='2')
plt.legend()
plt.show()

#6
#box plot for total runs in a match to check if there is match where they have score more
total_run=ipl_d['first_ings_score']+ipl_d['second_ings_score']
total_run
sns.boxplot(total_run)
plt.show()
# there are fw outliers but since the quantity is less it will not affect the overall data much
# further as this is a sporting data, it is a record and it should be strored for later record perpose
# so the outliers are not deleted

#7
stg=ipl_d.groupby(['stage','match_winner']).size().reset_index(name='wins')
stg_group=stg[stg['stage']=='Group']
stg_group=stg_group.sort_values(by='wins')
stg_p=stg[stg['stage']=='Playoff']
stg_p=stg_p.sort_values(by='wins')
plt.title('Group stage wins')
plt.barh(y=stg_group['match_winner'],width=stg_group['wins'])
plt.show()

plt.pie(stg_p['wins'])
plt.legend(stg_p['match_winner'])
plt.show()

#8

Player_cont=ipl_d[['best_bowling','top_scorer','player_of_the_match']]

def contributer(a,b,c):
  if a==c:
    return 'bowl'
  if b==c:
    return 'bat'
  else:
    return 'overall'
Player_cont['contributer']=pd.apply(contributer,Player_cont['best_bowling'],Player_cont['top_scorer'],Player_cont['player_of_the_match'])

#9
'''
* the data set provided is a very clear data set with proper dattypes and
  without missing values and without duplicates.
  From the toss winning pattern we can see most of the times the toss winner wants to field first
  This suggest that there will be due in the night and batting will be easier then.
* The top scorer is jos butler with the maximum heightest score
* From the scatter plot is is suggested that most of the ings has lost more than 2 wickets
* There is no prover trend in score per ings as matches progress but in general first ing score is slightly greater than second ings
* The average score of first ings in greater than averge score of second ings in most of the grounds, this may suggets that considering fielding is not a better option.
* Most of the matches the total score for both ings is between 300 to 370 with few above 400 and below 140
* Gujarat team has the most group stage wins and they have also the winners of ipl.So good form in group stages helps
* Bangalore , Gujarat and rajastan as has won 1 playoffs.
'''