# -*- coding: utf-8 -*-
"""pda_ia1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lb57TDTiX-woTLvFwqB1pp-gYhslV2ZO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

df=pd.read_csv('https://raw.githubusercontent.com/Deepsphere-AI/LVA-Batch5-Assessment/main/expenses.csv')

df.info()

df.head()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

df.isnull().sum()

median_bmi=df['bmi'].median()
df['bmi']=df['bmi'].fillna(median_bmi)

df.isnull().sum()

df.head(10)

cat_col=[x for x in df.select_dtypes(include=['object']).columns]
for c in cat_col:
  plt.figure(figsize=(10,5))
  df[c].value_counts().plot(kind='bar')
  plt.title(f'bar chart of {c}')
  plt.xlabel(f'{c}')
  plt.ylabel('frequency')
  plt.show()

num_col=[x for x in df.select_dtypes(include=['int64','float64']).columns]
for n in num_col:
  plt.figure(figsize=(10,5))
  sns.histplot(df[n])
  plt.title(f'histogram chart of {n}')
  plt.xlabel(f'{n}')
  plt.ylabel('frequency')
  plt.show()

for i in range(len(num_col)):
  for j in range(i+1,len(num_col)):
    plt.figure(figsize=(10,5))
    sns.scatterplot(data=df,x=num_col[i],y=num_col[j])
    plt.title(f'scatter chart of {i} and {j}')
    plt.xlabel(f'{i}')
    plt.ylabel(j)
    plt.show()

#corr
cor_mat=df[num_col].corr()
cor_mat

#heatmap
plt.figure(figsize=(10,5))
sns.heatmap(cor_mat,cmap='coolwarm',annot=True)
plt.title('heat map of corrilation')
plt.show()

'''
Insight : amoung all the numeric columns the number of children has the leat high positive influence on charges
this may be beacuse as it doesnt affect the health condition of the individual.
But age as highest correlation which means as you get old we have more disease prone.
'''

#outlier
num_col=[x for x in df.select_dtypes(include=['int64','float64']).columns]
for n in num_col:
  plt.figure(figsize=(10,5))
  sns.boxplot(df[n])
  plt.title(f'box plot of {n}')
  plt.xlabel(f'{n}')
  plt.ylabel('frequency')
  plt.show()

#encoding of cat
le=LabelEncoder()
for i in cat_col:
  df[i]=le.fit_transform(df[i])

df.head()

#split data
x=df.drop(columns='charges')
y=df['charges']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#scaling
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

#model
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)

#evaluation
mse=mean_squared_error(y_test,y_pred)
print(f'mse {mse}')
rmse=mean_squared_error(y_test,y_pred,squared=False)
print(f'rmse {rmse}')
r2s=r2_score(y_test,y_pred)
print(f'r2_score {r2s}')

corr_after_encoding=df.corr()
plt.figure(figsize=(10,5))
sns.heatmap(corr_after_encoding,cmap='coolwarm',annot=True)
plt.title('heat map of corrilation')
plt.show()

'''
Insights :
The charges are gender,regionand children nuteral that is very less impact.
But smoker have most impact as they are most prone for chronic diseases and followed by age
'''